### ISSUE TITLE
Bug List 우선 순위

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#64]
1/8 월
- [ ] iOS의 경우 앱의 위치 정보 접근을 '앱을 사용하는 동안' 및  '항상' 중 '항상' 쓸 수 있도록 되어야 합니다. CBT 참가자들 대부분은 걸음 수 카운트가 되지 않는 문제를 제기하고 있습니다.
- [ ] 누적 걸음 수 카운트는 '유저 걸음 수' + '보너스 걸음 쿠폰 획득시 해당 보너스 걸음만큼' 으로 결정됩니다. 현재는 보너스 걸음 쿠폰을 챌린지에 적용할 때만 누적 걸음 수가 카운트 되고 있습니다. 수정 부탁드립니다.

논의해야 할 사항
- [ ] 걸음 수 측정을 위해 iOS에서는 App 설정에서 '위치 정보 접근' 허용 시 최초에 유저에게 권한 요청함. 이후 요청은 없음. 유저가 만약 '항상 허용'을 하지 않는 경우엔 걸음 수 카운트가 아예 되지 않도록 개발되었음 -> 이대로 진행할 것인지. 이대로 진행한다면 유저에게 안내가 필요함. 이는, iOS의 설정 - 개인정보보호-GPS에서 GPS를 꺼버리는 경우 역시 동일함.
- [ ] 걸음 수가 원상 복구 되는 문제: ID: smilesoft327@icloud.com / iPhone6 에서 발생했습니다.
- [ ] 유저가 실제로 걸은 걸음 수가 누적 걸음 수에 반영되는 것과 챌린지에 반영되는 것의 차이가 발생하고 있습니다.
- [ ] 실제로 걸은 걸음수보다 적은 경우: 알고리즘에 대한 의논이 요구됨.

1/9 화
- [ ] 챌린지 진행 타임라인에 따른 챌린지 status 및 navigation. 홈과 마이챌린지 동기화: 카운트 변경 버튼, 챌린지 시작 전/진행 중/결제/추첨/당첨자 결제에 따른 화면 수정 후 반영. 
- [ ] 홈 및 (챌린지, 마이챌린지)챌린지 상세 페이지에서 추천 챌린지 클릭 시 해당 챌린지 상세 페이지로 이동해야 합니다.
- [ ] 마이챌린지에서 카운트 변경 버튼 클릭 시 카운트 가능/불가능 챌린지 구분 및 상황에 따른 멘트 변경 요망
- [ ] 홈 화면(#28 )의 이슈 전부

1/10 수
- [ ] 결제 이슈(#52 )의 이슈 전부

1/11 목
- [ ] 챌린지 참가 신청 후, 마이챌린지-참가중인 챌린지에 진입했을 때, 챌린지 리스트에 중복되는 챌린지가 나타나는 문제가 있습니다. 수정 부탁드립니다.
- [ ] 얼럿 메시지에 한글 -> 일본어 변경
- [ ] 퀴즈 화면: 유저가 퀴즈 답안 입력 시, iOS에서는 답안 제출 버튼이 키보드에 가려져 있습니다. 안드로이드에서처럼 키보드 위로 답안 제출 버튼이 함께 올라오게 변경 부탁드립니다.
- [ ] 친구 앱초대 공유시 보여지는 이미지 파일 및 텍스트 문구(유저의 추천인 코드 앞에 + 가 붙어 있음) 수정 부탁드립니다.

1/12 금
- [ ] 종료된 챌린지 피드백 작성 후 등록 및 SNS 공유 (이미지 수 제한 및 텍스트 제한)
- [ ] admin 및 sponsor web 정의 (csv 추출 및 보여줄 데이터 표시)
  

CBT 기간 동안 발견된 문제 & 개선사항
 - [ ] App에 접속 중인 유저들에겐 새로운 공지(notice)가 올라와도 N(NEW) 표시가 나타나지 않음
 - [ ] GetWalk guide 에 이미지 업로드 가능하도록 변경
 - [ ] Terms of use(이용약관)이 App 상에서 11조 이상부터는 숫자 두 글자 간격이 넓어져서 표시됨
 - [ ] Admin web에서 표시되는 한글 -> 영어
- [ ] 설정: 이용약관 텍스트 수정
- [ ] 가이드 부재
- [ ] 공지 테스트 요망
- [ ] 문의하기: 카테고리 선택시 확인 버튼 요망(확인 버튼이 없어서 문의 작성이 되지 않고 있음)
- [ ] 마이페이지-결제내역 클릭 시 리워드 상세 페이지 이동 확인 안 됨
- [ ] QR챌린지 (챌린지리스트의 상세페이지 및 마이챌린지의 상세페이지 순서)
- [ ] QR code 성공적으로 스캔된 경우: 안내 멘트 표시
- [ ] 상품 결제시 (-) 로 표시되는 금액이 틀립니다
- [ ] 상품 수령 버튼 클릭 안 되고 있음
- [ ] noti: 한글 표시 및 상세 클릭 시 이동 없음
- [ ] noti: 챌린지 status에 따른 push 메시지 확인 요망
- [ ] #28 이슈 중 체크되지 않은 항목
- [ ] #52 이슈 중 체크되지 않은 항목
- [ ] QR map 크게 보는 경우: QR point map 확대/축소가 화면에 대한 확대 축소로 보입니다. 확인해 주세요
- [ ] 회원 가입시 이용약관 및 개인 정보 보호 정책이 표시되는 항목에서 각 세부사항들에 줄바꿈이 없습니다. 전달드린 양식에 맞추어 줄 바꿈 들어갈 수 있도록 변경해주세요.

**Comment by Hyungseok-Seong** [comment]
1/8 월
개발사항 완료됨. 확인됨.

논의해야 할 사항
- 걸음 수 측정을 위해 iOS에서는 App 설정에서 '위치 정보 접근' 허용 시 최초에 유저에게 권한 요청함. 이후 요청은 없음. 유저가 만약 '항상 허용'을 하지 않는 경우엔 걸음 수 카운트가 아예 되지 않도록 개발되었음 -> 이대로 진행할 것인지. 이대로 진행한다면 유저에게 안내가 필요함. 이는, iOS의 설정 - 개인정보보호-GPS에서 GPS를 꺼버리는 경우 역시 동일함.
- 걸음 수가 원상 복구 되는 문제: ID: smilesoft327@icloud.com / iPhone6 에서 발생했습니다.
- 유저가 실제로 걸은 걸음 수가 누적 걸음 수에 반영되는 것과 챌린지에 반영되는 것의 차이가 발생하고 있습니다.
- 실제로 걸은 걸음수보다 적은 경우: 알고리즘에 대한 의논이 요구됨.

**Comment by Hyungseok-Seong** [comment]
CBT 기간 동안 발견된 문제 & 개선사항
- App에 접속 중인 유저들에겐 새로운 공지(notice)가 올라와도 N(NEW) 표시가 나타나지 않음
- GetWalk guide 에 이미지 업로드 가능하도록 변경
- Terms of use(이용약관)이 App 상에서 11조 이상부터는 숫자 두 글자 간격이 넓어져서 표시됨
- Admin web에서 표시되는 한글 -> 영어

**Comment by Hyungseok-Seong** [comment]
- 설정: 이용약관 텍스트 수정
 - 가이드 부재
 - 공지 테스트 요망
 - 문의하기: 카테고리 선택시 확인 버튼 요망(확인 버튼이 없어서 문의 작성이 되지 않고 있음)
 - 마이페이지-결제내역 클릭 시 리워드 상세 페이지 이동 확인 안 됨
 - QR챌린지 (챌린지리스트의 상세페이지 및 마이챌린지의 상세페이지 순서)
 - QR code 성공적으로 스캔된 경우: 안내 멘트 표시
 - 상품 결제시 (-) 로 표시되는 금액이 틀립니다
 - 상품 수령 버튼 클릭 안 되고 있음
 - noti: 한글 표시 및 상세 클릭 시 이동 없음
 - noti: 챌린지 status에 따른 push 메시지 확인 요망
 - #28 이슈 중 체크되지 않은 항목
 - #52  이슈 중 체크되지 않은 항목
 - QR map 크게 보는 경우: QR point map 확대/축소가 화면에 대한 확대 축소로 보입니다. 확인해 주세요

**Comment by Hyungseok-Seong** [comment]
- 회원 가입시 이용약관 및 개인 정보 보호 정책이 표시되는 항목에서 각 세부사항들에 줄바꿈이 없습니다. 전달드린 양식에 맞추어 줄 바꿈 들어갈 수 있도록 변경해주세요.
