### ISSUE TITLE
타임표시, 잔수량표시, 걸음수 표시

### ISSUE THREAD

**Issue by gracemj** [gracemj/getwalk#83]
![image](https://user-images.githubusercontent.com/14939610/35030490-75106f88-fba2-11e7-957b-8bd6d2585034.png)

- [ ] 1. #78 이슈와 중복됩니다. 챌린지 상세도 같이 적용해주세요

- [ ] 2. #78 이슈와 중복됩니다. 챌린지 상세도 같이 적용해주세요. 챌린지 상세에는 숫자와 일, 시, 분등의 단위의 간격과 폰트크기도 홈과는 다르네요.

- [ ] 3.챌린지 상세와 홈화면의 상품수량 디자인이 다릅니다. 확인해주세요.

![image](https://user-images.githubusercontent.com/14939610/35036063-7dd8f78e-fbb6-11e7-8856-a615ba33f915.png)

- [ ] '타임종류','상품수량' 텍스트(#ACB4BD)와  숫자 옆의 표시텍스트(#858D95)는 같은 크기의 폰트이고 칼라값이 다릅니다.
