### ISSUE TITLE
공유하기 문제 (app 친구 초대 및 피드백 공유)

### ISSUE THREAD

**Issue by Hyungseok-Seong** [gracemj/getwalk#90]
공유하기시 이미지 , 텍스트 내용을 공유할 수 있는 앱, 없는 앱 구분하여 전달 주세요.

- [ ] 앱 친구 초대(#41 ): LINE, SMS
- [ ] 피드백 공유(#40 ): Twitter, Facebook, Instagram

**Comment by applicatteam** [comment]
- [ ] 앱 친구 초대(#41 ): LINE, SMS
- [ ] 피드백 공유(#40 ): Twitter, Facebook, Instagram
